const cars = [
  {
    id: 1,
    name: "Audi A1 S-Line",
    src: "/public/images/Audi.jpg ",
    rent: "$45",
    model: "Audi",
    mark: "A1",
    year: "2012",
    Doors: "4/5",
    ac: "Yes",
    transmision: "Manual",
    fuel: "Gasoline",
  },
  {
    id: 2,
    name: "VW Golf 6",
    src: "/public/images/Golf.jpg",
    rent: "$37",
    model: "Golf 6",
    mark: "Volkswagen",
    year: "2008",
    Doors: "4/5",
    ac: "Yes",
    transmision: "Manual",
    fuel: "Diesel",
  },
  {
    id: 3,
    name: "Toyota Camry",
    src: "/public/images/toyotacamry.jpg",
    rent: "$30",
    model: "Camry",
    mark: "Toyota",
    year: "2006",
    Doors: "4/5",
    ac: "Yes",
    transmision: "Automatic",
    fuel: "Hybrid",
  },
  {
    id: 4,
    name: "BMW 320 ModernLine",
    src: "/public/images/Audi.jpg ",
    rent: "$35",
    model: "320",
    mark: "BMW",
    year: "2012",
    Doors: "4/5",
    ac: "Yes",
    transmision: "Manual",
    fuel: "Diesel",
  },

  {
    id: 5,
    name: "Mercedes-Benz GLK",
    src: "/public/images/Mercedes.jpg",
    rent: "$50",
    model: "Benz GLK",
    mark: "Mercedes",
    year: "2006",
    Doors: "4/5",
    ac: "Yes",
    transmision: "Manual",
    fuel: "Diesel",
  },
  {
    id: 6,
    name: "VW Passat CC",
    src: "/public/images/Passat.jpg",
    rent: "$25",
    model: "Passat CC",
    mark: "Volkswagen",
    year: "2008",
    Doors: "4/5",
    ac: "Yes",
    transmision: "Automatic",
    fuel: "Gasoline",
  },
];

export default cars;
