import { AiOutlineStar } from "react-icons/ai";
import { LiaCarSideSolid } from "react-icons/lia";
import { GrManual } from "react-icons/gr";
import { BiGasPump } from "react-icons/bi";
import { GiSteeringWheel } from "react-icons/gi";
const cars = [
  {
    id: 1,
    Name: "Audi A1",
    rent_price: "$45",
    model: "Audi",
    rating: "4/5",
    type: "Manual",
    gas: "Diesel",
    src: "/images/audiBox.png",
    icon: <LiaCarSideSolid className="text-[30px]" />,
    manual: <GiSteeringWheel className="text-[30px]" />,
    gas_icon: <BiGasPump className="text-[30px]" />,
  },
  {
    id: 2,
    Name: "Golf 6",
    rent_price: "$37",
    model: "VW",
    rating: "4/5",
    type: "Manual",
    gas: "Diesel",
    src: "/images/Golf-6.png",
    icon: <LiaCarSideSolid className="text-[30px]" />,
    manual: <GiSteeringWheel className="text-[30px]" />,
    gas_icon: <BiGasPump className="text-[30px]" />,
  },
  {
    id: 3,
    Name: "Toyota",
    rent_price: "$30",
    model: "Camry",
    rating: "4/5",
    type: "Manual",
    gas: "Diesel",
    src: "/images/toyota-box.png",
    icon: <LiaCarSideSolid className="text-[30px]" />,
    manual: <GiSteeringWheel className="text-[30px]" />,
    gas_icon: <BiGasPump className="text-[30px]" />,
  },
  {
    id: 4,
    Name: "BMW 320",
    rent_price: "$35",
    model: "ModernLine",
    rating: "4/5",
    type: "Manual",
    gas: "Diesel",
    src: "/images/Bmw-box.png",
    icon: <LiaCarSideSolid className="text-[30px]" />,
    manual: <GiSteeringWheel className="text-[30px]" />,
    gas_icon: <BiGasPump className="text-[30px]" />,
  },
  {
    id: 5,
    Name: "Mercedes",
    rent_price: "$50",
    model: "Benz GLK",
    rating: "4/5",
    type: "Manual",
    gas: "Diesel",
    src: "/images/Benz-box.png",
    icon: <LiaCarSideSolid className="text-[30px]" />,
    manual: <GiSteeringWheel className="text-[30px]" />,
    gas_icon: <BiGasPump className="text-[30px]" />,
  },
  {
    id: 6,
    Name: "VW Passat",
    rent_price: "$25",
    model: "CC",
    rating: "4/5",
    type: "Manual",
    gas: "Diesel",
    src: "/images/Passat-box.png",
    icon: <LiaCarSideSolid className="text-[30px]" />,
    manual: <GiSteeringWheel className="text-[30px]" />,
    gas_icon: <BiGasPump className="text-[30px]" />,
  },
  // Additional cars
  {
    id: 7,
    Name: "Ford Focus",
    rent_price: "$32",
    model: "Focus",
    rating: "4/5",
    type: "Manual",
    gas: "Petrol",
    src: "/images/focus.jpg",
    icon: <LiaCarSideSolid className="text-[30px]" />,
    manual: <GiSteeringWheel className="text-[30px]" />,
    gas_icon: <BiGasPump className="text-[30px]" />,
  },
  {
    id: 8,
    Name: "Honda Civic",
    rent_price: "$33",
    model: "Civic",
    rating: "4/5",
    type: "Manual",
    gas: "Petrol",
    src: "/images/honda.jpg",
    icon: <LiaCarSideSolid className="text-[30px]" />,
    manual: <GiSteeringWheel className="text-[30px]" />,
    gas_icon: <BiGasPump className="text-[30px]" />,
  },
  {
    id: 9,
    Name: "Hyundai Elantra",
    rent_price: "$28",
    model: "Elantra",
    rating: "4/5",
    type: "Manual",
    gas: "Petrol",
    src: "/images/hyundai.jpg",
    icon: <LiaCarSideSolid className="text-[30px]" />,
    manual: <GiSteeringWheel className="text-[30px]" />,
    gas_icon: <BiGasPump className="text-[30px]" />,
  },
  {
    id: 10,
    Name: "Nissan Altima",
    rent_price: "$31",
    model: "Altima",
    rating: "4/5",
    type: "Manual",
    gas: "Petrol",
    src: "/images/nissan.jpg",
    icon: <LiaCarSideSolid className="text-[30px]" />,
    manual: <GiSteeringWheel className="text-[30px]" />,
    gas_icon: <BiGasPump className="text-[30px]" />,
  },

  {
    id: 11,
    Name: "Mazda 3",
    rent_price: "$34",
    model: "Mazda3",
    rating: "4/5",
    type: "Manual",
    gas: "Petrol",
    src: "/images/mazda.jpg",
    icon: <LiaCarSideSolid className="text-[30px]" />,
    manual: <GiSteeringWheel className="text-[30px]" />,
    gas_icon: <BiGasPump className="text-[30px]" />,
  },
  {
    id: 12,
    Name: "Kia Optima",
    rent_price: "$29",
    model: "Optima",
    rating: "4/5",
    type: "Manual",
    gas: "Petrol",
    src: "/images/kia.jpg",
    icon: <LiaCarSideSolid className="text-[30px]" />,
    manual: <GiSteeringWheel className="text-[30px]" />,
    gas_icon: <BiGasPump className="text-[30px]" />,
  },
];

const star = {
  stars: [
    <AiOutlineStar key={1} className="text-[18px]" />,
    <AiOutlineStar key={2} className="text-[18px] " />,
    <AiOutlineStar key={3} className="text-[18px]" />,
    <AiOutlineStar key={4} className="text-[18px]" />,
    <AiOutlineStar key={5} className="text-[18px]" />,
  ],
};
export { cars, star };
